# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJuwZVIEd_nVdtMEuMaX5T9o8Sdd4HNC
"""

# ================================================================
# LBM Ink-on-Paper — Full Physics Kernel
# D2Q9 + Fiber Network + Laplace Evaporation
# ================================================================

import torch
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ──────────────────────────────────────────────────────
# Parameters
# ──────────────────────────────────────────────────────
Nx, Ny = 512, 512
tau = 0.85
omega = 1.0 / tau
rho0 = 1.0
evap_coeff = 0.0008
drop_radius = 16
steps = 2000
snap_at = [0, 200, 500, 1000, 1500, 1999]

# ──────────────────────────────────────────────────────
# D2Q9 Lattice
# ──────────────────────────────────────────────────────
c = torch.tensor([
    [0,0],[1,0],[0,1],[-1,0],[0,-1],
    [1,1],[-1,1],[-1,-1],[1,-1]
], device=device, dtype=torch.float32)

w = torch.tensor([
    4/9, 1/9, 1/9, 1/9, 1/9,
    1/36, 1/36, 1/36, 1/36
], device=device, dtype=torch.float32)

opposite = torch.tensor([0, 3, 4, 1, 2, 7, 8, 5, 6], device=device, dtype=torch.long)

# ──────────────────────────────────────────────────────
# Fiber Deposition Model (Koponen et al.)
# ──────────────────────────────────────────────────────
def generate_fiber_network(nx, ny, n_fibers=4000,
                           fiber_length=35, fiber_width=2,
                           seed=42):
    """
    Random fiber deposition → physically-based κ field.
    Each fiber is a line segment with random position & orientation,
    stamped onto the grid. Local solid fraction = κ.
    """
    np.random.seed(seed)
    field = np.zeros((nx, ny), dtype=np.float32)

    for _ in range(n_fibers):
        x0 = np.random.uniform(0, nx)
        y0 = np.random.uniform(0, ny)
        theta = np.random.uniform(0, np.pi)
        length = max(5, np.random.normal(fiber_length, fiber_length * 0.25))

        n_steps = int(length)
        ts = np.linspace(-length / 2, length / 2, n_steps)
        xs = (x0 + ts * np.cos(theta)).astype(int) % nx
        ys = (y0 + ts * np.sin(theta)).astype(int) % ny

        hw = fiber_width // 2
        for dx in range(-hw, hw + 1):
            for dy in range(-hw, hw + 1):
                if dx * dx + dy * dy <= (fiber_width / 2 + 0.5) ** 2:
                    field[(xs + dx) % nx, (ys + dy) % ny] += 1

    field = field / max(field.max(), 1)
    return field

print("Generating fiber network...")
kappa_np = generate_fiber_network(Nx, Ny)
kappa = torch.tensor(kappa_np, dtype=torch.float32, device=device)
kappa = 0.05 + 0.55 * kappa  # map to [0.05, 0.60]
print(f"  κ range: [{kappa.min().item():.3f}, {kappa.max().item():.3f}]")

# ──────────────────────────────────────────────────────
# LBM Core Functions
# ──────────────────────────────────────────────────────
def equilibrium(rho, u):
    cu = torch.einsum('ic,cxy->ixy', c, u)
    u_sq = 0.5 * (u[0]**2 + u[1]**2)
    return w.view(9,1,1) * rho.unsqueeze(0) * (
        1.0 + 3.0*cu + 4.5*cu**2 - 3.0*u_sq.unsqueeze(0))

def stream(f):
    f_s = torch.zeros_like(f)
    for i in range(9):
        f_s[i] = torch.roll(f[i], shifts=(int(c[i,0]), int(c[i,1])), dims=(0,1))
    return f_s

def bounceback(f, kappa):
    return (1.0 - kappa).unsqueeze(0) * f + kappa.unsqueeze(0) * f[opposite]

# ──────────────────────────────────────────────────────
# Laplace Vapor Diffusion Evaporation
# ──────────────────────────────────────────────────────
def compute_evaporation_laplace(rho, rho0, kappa, evap_coeff,
                                 c_sat=1.0, c_amb=0.3, iters=60):
    """
    Solve ∇²c = 0 for vapor concentration above the surface.
    BC: c = c_sat on wet cells, relaxes toward c_amb elsewhere.
    Evaporation flux J = |∇c| at wet boundary.
    """
    excess = (rho - rho0).clamp(min=0)
    wet = excess > 0.005

    if wet.sum() < 5:
        return torch.zeros_like(rho)

    # Initialize vapor field
    c_vapor = torch.ones_like(rho) * c_amb
    c_vapor[wet] = c_sat
    wet_float = wet.float()

    # Jacobi iteration for Laplace equation
    for _ in range(iters):
        c_new = 0.25 * (
            torch.roll(c_vapor, 1, 0) + torch.roll(c_vapor, -1, 0) +
            torch.roll(c_vapor, 1, 1) + torch.roll(c_vapor, -1, 1)
        )
        # Pin wet cells to saturation
        c_new = c_new * (1 - wet_float) + c_sat * wet_float
        c_vapor = c_new

    # Flux = gradient magnitude
    grad_x = (torch.roll(c_vapor, -1, 0) - torch.roll(c_vapor, 1, 0)) / 2
    grad_y = (torch.roll(c_vapor, -1, 1) - torch.roll(c_vapor, 1, 1)) / 2
    J = torch.sqrt(grad_x**2 + grad_y**2)

    # Only evaporate from wet cells, modulate by pore openness
    pore_factor = 1.0 - 0.3 * kappa
    J = evap_coeff * J * wet_float * pore_factor

    # Stability: don't remove more than 10% per step
    J = torch.min(J, excess * 0.1)
    return J

# ──────────────────────────────────────────────────────
# Initial Condition
# ──────────────────────────────────────────────────────
Y, X = torch.meshgrid(
    torch.arange(Nx, device=device, dtype=torch.float32),
    torch.arange(Ny, device=device, dtype=torch.float32), indexing='ij')
r = torch.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)

rho = torch.ones((Nx, Ny), device=device) * rho0
rho[r < drop_radius] = 1.5
u = torch.zeros((2, Nx, Ny), device=device)
f = equilibrium(rho, u)

# ──────────────────────────────────────────────────────
# Main Loop
# ──────────────────────────────────────────────────────
snapshots = []

print(f"Running {steps} steps...")
for step in range(steps):
    # Macroscopic quantities
    rho = f.sum(dim=0)
    momentum = torch.einsum('ic,ixy->cxy', c, f)
    u = momentum / (rho.unsqueeze(0) + 1e-10)

    # Collision + porous bounce-back + streaming
    feq = equilibrium(rho, u)
    f = stream(bounceback(f - omega * (f - feq), kappa))

    # Laplace-solved evaporation
    rho_post = f.sum(dim=0)
    J = compute_evaporation_laplace(rho_post, rho0, kappa, evap_coeff)
    f -= (J / (rho_post + 1e-10)).unsqueeze(0) * f

    if step in snap_at:
        rho_snap = f.sum(dim=0)
        excess = (rho_snap - rho0).clamp(min=0).cpu().numpy()
        mass = excess.sum()
        snapshots.append((step, excess.copy()))
        print(f"  Step {step:4d} | excess max={excess.max():.4f} | "
              f"total mass={mass:.1f}")

print("Done.")

# ──────────────────────────────────────────────────────
# Visualization
# ──────────────────────────────────────────────────────
ink_cmap = LinearSegmentedColormap.from_list('ink', [
    (1.0, 0.98, 0.94),
    (0.6, 0.62, 0.7),
    (0.25, 0.22, 0.38),
    (0.05, 0.03, 0.1)])

# --- Fiber network ---
fig, ax = plt.subplots(figsize=(6, 6))
ax.imshow(kappa.cpu().numpy(), cmap='bone_r', interpolation='nearest')
ax.set_title("Paper Fiber Network (κ field)", fontsize=13, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.show()

# --- Time evolution ---
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, (step, excess) in zip(axes.flat, snapshots):
    vmax = max(excess.max() * 0.85, 0.005)
    ax.imshow(excess, cmap=ink_cmap, vmin=0, vmax=vmax, interpolation='bilinear')
    ax.set_title(f"Step {step}", fontsize=11)
    ax.axis('off')
fig.suptitle("Ink Spreading with Fiber Network + Laplace Evaporation",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# --- Final hero render with paper texture ---
final_rho = f.sum(dim=0)
final_excess = (final_rho - rho0).clamp(min=0).cpu().numpy()

# Paper texture from the fiber field itself
paper_base = 1.0 - 0.06 * kappa_np  # fibers slightly darker
paper_grain = np.random.normal(0, 0.01, (Nx, Ny))
paper = paper_base + paper_grain

ink_opacity = np.clip(final_excess / max(final_excess.max() * 0.7, 0.001), 0, 1)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(paper, cmap='bone', vmin=0.88, vmax=1.05, interpolation='bilinear')
ax.imshow(final_excess, cmap=ink_cmap, vmin=0, vmax=max(final_excess.max()*0.75, 0.001),
          interpolation='bilinear', alpha=ink_opacity * 0.95)
ax.set_title("Final — Ink on Paper (Physics-Based)", fontsize=15, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.show()

# ================================================================
# LBM Ink — Tuned for Coffee Ring Formation
# Lower pigment diffusion + stronger evaporation
# ================================================================

import torch
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ──────────────────────────────────────────────────────
# Parameters — TUNED for coffee ring
# ──────────────────────────────────────────────────────
Nx, Ny = 512, 512
tau_water = 0.75          # lower water viscosity → spreads faster
tau_pigment = 1.5         # MUCH higher → pigment diffuses slowly
                          # D_pig = (1.5 - 0.5)/3 = 0.033 vs 0.133 before
omega_w = 1.0 / tau_water
omega_p = 1.0 / tau_pigment
rho0 = 1.0
evap_coeff = 0.000001        # stronger evaporation → stronger outward flow
drop_radius = 20
pigment_radius = 18
steps = 3000
snap_at = [0, 300, 800, 1500, 2200, 2999]

# ──────────────────────────────────────────────────────
# D2Q9
# ──────────────────────────────────────────────────────
c = torch.tensor([
    [0,0],[1,0],[0,1],[-1,0],[0,-1],
    [1,1],[-1,1],[-1,-1],[1,-1]
], device=device, dtype=torch.float32)

w = torch.tensor([
    4/9, 1/9, 1/9, 1/9, 1/9,
    1/36, 1/36, 1/36, 1/36
], device=device, dtype=torch.float32)

opposite = torch.tensor([0, 3, 4, 1, 2, 7, 8, 5, 6], device=device, dtype=torch.long)

# ──────────────────────────────────────────────────────
# Fiber Network
# ──────────────────────────────────────────────────────
def generate_fiber_network(nx, ny, n_fibers=4000,
                           fiber_length=35, fiber_width=2, seed=42):
    np.random.seed(seed)
    field = np.zeros((nx, ny), dtype=np.float32)
    for _ in range(n_fibers):
        x0 = np.random.uniform(0, nx)
        y0 = np.random.uniform(0, ny)
        theta = np.random.uniform(0, np.pi)
        length = max(5, np.random.normal(fiber_length, fiber_length * 0.25))
        n_steps = int(length)
        ts = np.linspace(-length/2, length/2, n_steps)
        xs = (x0 + ts * np.cos(theta)).astype(int) % nx
        ys = (y0 + ts * np.sin(theta)).astype(int) % ny
        hw = fiber_width // 2
        for dx in range(-hw, hw + 1):
            for dy in range(-hw, hw + 1):
                if dx*dx + dy*dy <= (fiber_width/2 + 0.5)**2:
                    field[(xs+dx) % nx, (ys+dy) % ny] += 1
    return field / max(field.max(), 1)

print("Generating fibers...")
kappa_np = generate_fiber_network(Nx, Ny)
kappa = torch.tensor(kappa_np, dtype=torch.float32, device=device)
kappa = 0.05 + 0.55 * kappa
kappa_pig = (kappa * 1.3).clamp(max=0.88)

# ──────────────────────────────────────────────────────
# LBM Functions
# ──────────────────────────────────────────────────────
def eq(scalar, u):
    cu = torch.einsum('ic,cxy->ixy', c, u)
    u_sq = 0.5 * (u[0]**2 + u[1]**2)
    return w.view(9,1,1) * scalar.unsqueeze(0) * (
        1.0 + 3.0*cu + 4.5*cu**2 - 3.0*u_sq.unsqueeze(0))

def stream(f):
    f_s = torch.zeros_like(f)
    for i in range(9):
        f_s[i] = torch.roll(f[i], shifts=(int(c[i,0]), int(c[i,1])), dims=(0,1))
    return f_s

def bounceback(f, k):
    return (1.0 - k).unsqueeze(0) * f + k.unsqueeze(0) * f[opposite]

# ──────────────────────────────────────────────────────
# Laplace Evaporation
# ──────────────────────────────────────────────────────
def compute_evaporation(rho, rho0, kappa, evap_coeff,
                        c_sat=1.0, c_amb=0.3, iters=80):
    excess = (rho - rho0).clamp(min=0)
    wet = excess > 0.003
    if wet.sum() < 5:
        return torch.zeros_like(rho)

    c_vapor = torch.ones_like(rho) * c_amb
    c_vapor[wet] = c_sat
    wet_float = wet.float()

    for _ in range(iters):
        c_new = 0.25 * (
            torch.roll(c_vapor, 1, 0) + torch.roll(c_vapor, -1, 0) +
            torch.roll(c_vapor, 1, 1) + torch.roll(c_vapor, -1, 1))
        c_new = c_new * (1 - wet_float) + c_sat * wet_float
        c_vapor = c_new

    grad_x = (torch.roll(c_vapor, -1, 0) - torch.roll(c_vapor, 1, 0)) / 2
    grad_y = (torch.roll(c_vapor, -1, 1) - torch.roll(c_vapor, 1, 1)) / 2
    J = torch.sqrt(grad_x**2 + grad_y**2)
    J = evap_coeff * J * wet_float * (1.0 - 0.3 * kappa)
    J = torch.min(J, excess * 0.08)
    return J

# ──────────────────────────────────────────────────────
# Initial Conditions
# ──────────────────────────────────────────────────────
Y, X = torch.meshgrid(
    torch.arange(Nx, device=device, dtype=torch.float32),
    torch.arange(Ny, device=device, dtype=torch.float32), indexing='ij')
r = torch.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)

rho = torch.ones((Nx, Ny), device=device) * rho0
rho[r < drop_radius] = 1.5
u = torch.zeros((2, Nx, Ny), device=device)
f = eq(rho, u)

pigment = torch.zeros((Nx, Ny), device=device)
pigment[r < pigment_radius] = 1.0
g = eq(pigment, u)

# ──────────────────────────────────────────────────────
# Main Loop
# ──────────────────────────────────────────────────────
snaps_water = []
snaps_pigment = []

print(f"Running {steps} steps...")
for step in range(steps):
    # Water LBM
    rho = f.sum(dim=0)
    momentum = torch.einsum('ic,ixy->cxy', c, f)
    u = momentum / (rho.unsqueeze(0) + 1e-10)

    f = stream(bounceback(f - omega_w * (f - eq(rho, u)), kappa))

    # Evaporation (water only)
    rho_post = f.sum(dim=0)
    J = compute_evaporation(rho_post, rho0, kappa, evap_coeff)
    f -= (J / (rho_post + 1e-10)).unsqueeze(0) * f

    # Pigment LBM (no evaporation)
    pigment = g.sum(dim=0).clamp(min=0)
    g = stream(bounceback(g - omega_p * (g - eq(pigment, u)), kappa_pig))

    if step in snap_at:
        rho_now = f.sum(dim=0)
        excess = (rho_now - rho0).clamp(min=0)
        pig_now = g.sum(dim=0).clamp(min=0)
        snaps_water.append((step, excess.cpu().numpy().copy()))
        snaps_pigment.append((step, pig_now.cpu().numpy().copy()))
        print(f"  Step {step:4d} | water max={excess.max().item():.4f} "
              f"mass={excess.sum().item():.1f} | "
              f"pig max={pig_now.max().item():.4f} "
              f"mass={pig_now.sum().item():.1f}")

print("Done.")

# ──────────────────────────────────────────────────────
# Visualization
# ──────────────────────────────────────────────────────
ink_cmap = LinearSegmentedColormap.from_list('ink', [
    (1.0, 0.98, 0.94),
    (0.6, 0.62, 0.7),
    (0.25, 0.22, 0.38),
    (0.05, 0.03, 0.1)])

# --- Pigment evolution ---
fig, axes = plt.subplots(2, len(snap_at), figsize=(4*len(snap_at), 8))
for i, ((sw, water), (sp, pig)) in enumerate(zip(snaps_water, snaps_pigment)):
    vmax_w = max(water.max() * 0.85, 0.005)
    axes[0, i].imshow(water, cmap='Blues', vmin=0, vmax=vmax_w, interpolation='bilinear')
    axes[0, i].set_title(f"Step {sw}", fontsize=10)
    axes[0, i].axis('off')

    vmax_p = max(pig.max() * 0.85, 0.005)
    axes[1, i].imshow(pig, cmap=ink_cmap, vmin=0, vmax=vmax_p, interpolation='bilinear')
    axes[1, i].set_title(f"Step {sp}", fontsize=10)
    axes[1, i].axis('off')

axes[0, 0].set_ylabel("Water", fontsize=12)
axes[1, 0].set_ylabel("Pigment", fontsize=12)
fig.suptitle("Water Evaporates → Pigment Concentrates",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# --- Radial profile ---
final_pig = g.sum(dim=0).clamp(min=0).cpu().numpy()
final_water = (f.sum(dim=0) - rho0).clamp(min=0).cpu().numpy()

cx, cy = Nx//2, Ny//2
r_vals = np.sqrt((np.arange(Nx)[:,None] - cx)**2 + (np.arange(Ny)[None,:] - cy)**2)

max_r = 120
bins = np.arange(0, max_r, 1.0)
r_centers = 0.5 * (bins[:-1] + bins[1:])
pig_profile = np.zeros(len(r_centers))
water_profile = np.zeros(len(r_centers))

for j in range(len(r_centers)):
    mask = (r_vals >= bins[j]) & (r_vals < bins[j+1])
    if mask.sum() > 0:
        pig_profile[j] = final_pig[mask].mean()
        water_profile[j] = final_water[mask].mean()

fig, ax1 = plt.subplots(figsize=(10, 5))
ax1.plot(r_centers, pig_profile, color='#2c1654', linewidth=2.5, label='Pigment')
ax1.fill_between(r_centers, pig_profile, alpha=0.15, color='#2c1654')
ax1.set_xlabel('Radial distance from centre (lu)', fontsize=12)
ax1.set_ylabel('Pigment concentration', fontsize=12, color='#2c1654')

ax2 = ax1.twinx()
ax2.plot(r_centers, water_profile, color='#3d7ec7', linewidth=2, alpha=0.7,
         linestyle='--', label='Water excess')
ax2.set_ylabel('Water excess (ρ - ρ₀)', fontsize=12, color='#3d7ec7')

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, fontsize=11)
ax1.set_title("Radial Profile — Coffee Ring?", fontsize=13, fontweight='bold')
ax1.grid(True, alpha=0.2)
plt.tight_layout()
plt.show()

# --- Hero render ---
paper_base = 1.0 - 0.06 * kappa_np
paper = paper_base + np.random.normal(0, 0.01, (Nx, Ny))
ink_opacity = np.clip(final_pig / max(final_pig.max() * 0.65, 0.001), 0, 1)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(paper, cmap='bone', vmin=0.88, vmax=1.05, interpolation='bilinear')
ax.imshow(final_pig, cmap=ink_cmap, vmin=0, vmax=max(final_pig.max()*0.7, 0.001),
          interpolation='bilinear', alpha=ink_opacity * 0.95)
ax.set_title("Ink on Paper — Physics-Based", fontsize=15, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.show()

# ================================================================
# Physical Pinning — Tuned for Spreading + Roughening
# ================================================================

import torch
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Nx, Ny = 512, 512
tau = 0.75              # lower τ → less viscous → spreads easier
omega = 1.0 / tau
rho0 = 1.0
evap_coeff = 0.001
drop_radius = 20
steps = 2500
snap_at = [0, 200, 600, 1200, 1800, 2499]

# ──────────────────────────────────────────────────────
# D2Q9
# ──────────────────────────────────────────────────────
c = torch.tensor([
    [0,0],[1,0],[0,1],[-1,0],[0,-1],
    [1,1],[-1,1],[-1,-1],[1,-1]
], device=device, dtype=torch.float32)

w = torch.tensor([
    4/9, 1/9, 1/9, 1/9, 1/9,
    1/36, 1/36, 1/36, 1/36
], device=device, dtype=torch.float32)

opposite = torch.tensor([0, 3, 4, 1, 2, 7, 8, 5, 6], device=device, dtype=torch.long)

# ──────────────────────────────────────────────────────
# Fiber Network — tuned for balance
# ──────────────────────────────────────────────────────
def generate_fiber_network(nx, ny, n_fibers=3000,
                           fiber_length_mean=28, fiber_length_std=10,
                           fiber_width=2, seed=42):
    np.random.seed(seed)
    field = np.zeros((nx, ny), dtype=np.float32)

    for _ in range(n_fibers):
        x0 = np.random.uniform(0, nx)
        y0 = np.random.uniform(0, ny)
        theta = np.random.uniform(0, np.pi)
        length = max(5, np.random.normal(fiber_length_mean, fiber_length_std))
        n_steps = int(length)
        ts = np.linspace(-length/2, length/2, n_steps)
        xs = (x0 + ts * np.cos(theta)).astype(int) % nx
        ys = (y0 + ts * np.sin(theta)).astype(int) % ny
        hw = fiber_width // 2
        for dx in range(-hw, hw + 1):
            for dy in range(-hw, hw + 1):
                if dx*dx + dy*dy <= (fiber_width/2 + 0.5)**2:
                    field[(xs+dx) % nx, (ys+dy) % ny] += 1

    print(f"  Overlaps: min={field.min():.0f}, max={field.max():.0f}, "
          f"mean={field.mean():.2f}")

    # Gentler mapping: β=0.3 instead of 0.5
    # Single fiber → κ ≈ 0.26
    # Two fibers → κ ≈ 0.45
    # Three fibers → κ ≈ 0.59
    # Four+ fibers → κ ≈ 0.70+
    beta = 0.3
    kappa = 1.0 - np.exp(-beta * field)

    # Cap at 0.85 — even dense crossings aren't fully solid
    kappa = np.clip(kappa, 0.01, 0.85)

    return kappa, field

print("Generating fibers...")
kappa_np, overlap_np = generate_fiber_network(Nx, Ny)
kappa = torch.tensor(kappa_np, dtype=torch.float32, device=device)

open_frac = (kappa_np < 0.15).mean() * 100
mid_frac = ((kappa_np >= 0.15) & (kappa_np < 0.5)).mean() * 100
high_frac = (kappa_np >= 0.5).mean() * 100
print(f"  κ: [{kappa_np.min():.3f}, {kappa_np.max():.3f}]")
print(f"  Open (<0.15): {open_frac:.1f}% | Mid: {mid_frac:.1f}% | "
      f"Resistant (>0.5): {high_frac:.1f}%")

# ──────────────────────────────────────────────────────
# LBM Functions
# ──────────────────────────────────────────────────────
def eq(scalar, u):
    cu = torch.einsum('ic,cxy->ixy', c, u)
    u_sq = 0.5 * (u[0]**2 + u[1]**2)
    return w.view(9,1,1) * scalar.unsqueeze(0) * (
        1.0 + 3.0*cu + 4.5*cu**2 - 3.0*u_sq.unsqueeze(0))

def stream(f):
    f_s = torch.zeros_like(f)
    for i in range(9):
        f_s[i] = torch.roll(f[i], shifts=(int(c[i,0]), int(c[i,1])), dims=(0,1))
    return f_s

def bounceback(f, k):
    return (1.0 - k).unsqueeze(0) * f + k.unsqueeze(0) * f[opposite]

# ──────────────────────────────────────────────────────
# Laplace Evaporation
# ──────────────────────────────────────────────────────
def compute_evaporation(rho, rho0, kappa, evap_coeff,
                        c_sat=1.0, c_amb=0.3, iters=60):
    excess = (rho - rho0).clamp(min=0)
    wet = excess > 0.003
    if wet.sum() < 5:
        return torch.zeros_like(rho)
    c_vapor = torch.ones_like(rho) * c_amb
    c_vapor[wet] = c_sat
    wet_float = wet.float()
    for _ in range(iters):
        c_new = 0.25 * (
            torch.roll(c_vapor, 1, 0) + torch.roll(c_vapor, -1, 0) +
            torch.roll(c_vapor, 1, 1) + torch.roll(c_vapor, -1, 1))
        c_new = c_new * (1 - wet_float) + c_sat * wet_float
        c_vapor = c_new
    grad_x = (torch.roll(c_vapor, -1, 0) - torch.roll(c_vapor, 1, 0)) / 2
    grad_y = (torch.roll(c_vapor, -1, 1) - torch.roll(c_vapor, 1, 1)) / 2
    J = torch.sqrt(grad_x**2 + grad_y**2)
    J = evap_coeff * J * wet_float * (1.0 - 0.3 * kappa)
    J = torch.min(J, excess * 0.08)
    return J

# ──────────────────────────────────────────────────────
# Initial Condition — bigger drop, more pressure to push through
# ──────────────────────────────────────────────────────
Y, X = torch.meshgrid(
    torch.arange(Nx, device=device, dtype=torch.float32),
    torch.arange(Ny, device=device, dtype=torch.float32), indexing='ij')
r = torch.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)

rho = torch.ones((Nx, Ny), device=device) * rho0
# Smooth drop profile instead of hard edge — more stable
rho += 0.5 * torch.exp(-(r / drop_radius)**2)
u = torch.zeros((2, Nx, Ny), device=device)
f = eq(rho, u)

print(f"Initial rho: [{rho.min().item():.3f}, {rho.max().item():.3f}]")

# ──────────────────────────────────────────────────────
# Main Loop
# ──────────────────────────────────────────────────────
snapshots = []
print(f"\nRunning {steps} steps...")
for step in range(steps):
    rho = f.sum(dim=0)
    momentum = torch.einsum('ic,ixy->cxy', c, f)
    u = momentum / (rho.unsqueeze(0) + 1e-10)

    f = stream(bounceback(f - omega * (f - eq(rho, u)), kappa))

    rho_post = f.sum(dim=0)
    J = compute_evaporation(rho_post, rho0, kappa, evap_coeff)
    f -= (J / (rho_post + 1e-10)).unsqueeze(0) * f

    if step in snap_at:
        rho_now = f.sum(dim=0)
        excess = (rho_now - rho0).clamp(min=0)
        snapshots.append((step, excess.cpu().numpy().copy()))
        # Measure spread radius
        ex = excess.cpu().numpy()
        wet_cells = (ex > 0.005).sum()
        print(f"  Step {step:4d} | max={excess.max().item():.4f} "
              f"mass={excess.sum().item():.1f} | wet cells={wet_cells}")

print("Done.")

# ──────────────────────────────────────────────────────
# Visualization
# ──────────────────────────────────────────────────────
ink_cmap = LinearSegmentedColormap.from_list('ink', [
    (1.0, 0.98, 0.94), (0.6, 0.62, 0.7),
    (0.25, 0.22, 0.38), (0.05, 0.03, 0.1)])

# Fiber structure + κ histogram
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].imshow(overlap_np, cmap='hot', interpolation='nearest')
axes[0].set_title("Fiber Overlap Count")
axes[0].axis('off')
axes[1].imshow(kappa_np, cmap='bone_r', interpolation='nearest')
axes[1].set_title("κ Field")
axes[1].axis('off')
axes[2].hist(kappa_np.flatten(), bins=80, color='#3d5a80', alpha=0.8, density=True)
axes[2].set_xlabel('κ'); axes[2].set_ylabel('Density')
axes[2].set_title('κ Distribution')
axes[2].axvline(0.15, color='green', ls='--', alpha=0.5, label='Open')
axes[2].axvline(0.5, color='red', ls='--', alpha=0.5, label='Resistant')
axes[2].legend()
plt.tight_layout()
plt.show()

# Time evolution
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, (step, excess) in zip(axes.flat, snapshots):
    vmax = max(excess.max() * 0.85, 0.005)
    ax.imshow(excess, cmap=ink_cmap, vmin=0, vmax=vmax, interpolation='bilinear')
    ax.set_title(f"Step {step}", fontsize=11)
    ax.axis('off')
fig.suptitle("Physical Pinning via Fiber Crossings — No Heuristic Threshold",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Hero render
final_excess = (f.sum(dim=0) - rho0).clamp(min=0).cpu().numpy()
paper = (1.0 - 0.08 * kappa_np) + np.random.normal(0, 0.008, (Nx, Ny))
ink_opacity = np.clip(final_excess / max(final_excess.max() * 0.65, 0.001), 0, 1)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(paper, cmap='bone', vmin=0.85, vmax=1.05, interpolation='bilinear')
ax.imshow(final_excess, cmap=ink_cmap, vmin=0,
          vmax=max(final_excess.max()*0.7, 0.001),
          interpolation='bilinear', alpha=ink_opacity * 0.95)
ax.set_title("Ink on Paper — Emergent Pinning", fontsize=15, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.show()

# --- Zoomed comparison: boundary detail ---
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
cx, cy = Nx//2, Ny//2
# Find where the ink reaches
wet_mask = final_excess > 0.003
if wet_mask.any():
    wet_y, wet_x = np.where(wet_mask)
    # Zoom into a boundary region
    zx = min(wet_x.max() + 20, Nx)
    zy = int((wet_y.min() + wet_y.max()) / 2)
    z_half = 60
    sl_y = slice(max(zy-z_half, 0), min(zy+z_half, Ny))
    sl_x = slice(max(zx-z_half*2, 0), min(zx+20, Nx))

    axes[0].imshow(kappa_np[sl_y, sl_x], cmap='bone_r', interpolation='nearest')
    axes[0].set_title("Fiber Structure (zoom)")
    axes[0].axis('off')

    axes[1].imshow(final_excess[sl_y, sl_x], cmap=ink_cmap, vmin=0,
                   vmax=max(final_excess.max()*0.7, 0.001), interpolation='bilinear')
    axes[1].set_title("Ink Front (zoom) — pinning at fiber barriers")
    axes[1].axis('off')
else:
    axes[0].text(0.5, 0.5, "No wet cells", ha='center', va='center')
    axes[1].text(0.5, 0.5, "No wet cells", ha='center', va='center')

fig.suptitle("Boundary Detail — Front Roughening from κ Heterogeneity",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()