# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJuwZVIEd_nVdtMEuMaX5T9o8Sdd4HNC
"""

# ================================================================
# LBM Ink-on-Paper — Full Physics Kernel
# D2Q9 + Fiber Network + Laplace Evaporation
# ================================================================

import torch
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ──────────────────────────────────────────────────────
# Parameters
# ──────────────────────────────────────────────────────
Nx, Ny = 512, 512
tau = 0.85
omega = 1.0 / tau
rho0 = 1.0
evap_coeff = 0.0008
drop_radius = 16
steps = 2000
snap_at = [0, 200, 500, 1000, 1500, 1999]

# ──────────────────────────────────────────────────────
# D2Q9 Lattice
# ──────────────────────────────────────────────────────
c = torch.tensor([
    [0,0],[1,0],[0,1],[-1,0],[0,-1],
    [1,1],[-1,1],[-1,-1],[1,-1]
], device=device, dtype=torch.float32)

w = torch.tensor([
    4/9, 1/9, 1/9, 1/9, 1/9,
    1/36, 1/36, 1/36, 1/36
], device=device, dtype=torch.float32)

opposite = torch.tensor([0, 3, 4, 1, 2, 7, 8, 5, 6], device=device, dtype=torch.long)

# ──────────────────────────────────────────────────────
# Fiber Deposition Model (Koponen et al.)
# ──────────────────────────────────────────────────────
def generate_fiber_network(nx, ny, n_fibers=4000,
                           fiber_length=35, fiber_width=2,
                           seed=42):
    """
    Random fiber deposition → physically-based κ field.
    Each fiber is a line segment with random position & orientation,
    stamped onto the grid. Local solid fraction = κ.
    """
    np.random.seed(seed)
    field = np.zeros((nx, ny), dtype=np.float32)

    for _ in range(n_fibers):
        x0 = np.random.uniform(0, nx)
        y0 = np.random.uniform(0, ny)
        theta = np.random.uniform(0, np.pi)
        length = max(5, np.random.normal(fiber_length, fiber_length * 0.25))

        n_steps = int(length)
        ts = np.linspace(-length / 2, length / 2, n_steps)
        xs = (x0 + ts * np.cos(theta)).astype(int) % nx
        ys = (y0 + ts * np.sin(theta)).astype(int) % ny

        hw = fiber_width // 2
        for dx in range(-hw, hw + 1):
            for dy in range(-hw, hw + 1):
                if dx * dx + dy * dy <= (fiber_width / 2 + 0.5) ** 2:
                    field[(xs + dx) % nx, (ys + dy) % ny] += 1

    field = field / max(field.max(), 1)
    return field

print("Generating fiber network...")
kappa_np = generate_fiber_network(Nx, Ny)
kappa = torch.tensor(kappa_np, dtype=torch.float32, device=device)
kappa = 0.05 + 0.55 * kappa  # map to [0.05, 0.60]
print(f"  κ range: [{kappa.min().item():.3f}, {kappa.max().item():.3f}]")

# ──────────────────────────────────────────────────────
# LBM Core Functions
# ──────────────────────────────────────────────────────
def equilibrium(rho, u):
    cu = torch.einsum('ic,cxy->ixy', c, u)
    u_sq = 0.5 * (u[0]**2 + u[1]**2)
    return w.view(9,1,1) * rho.unsqueeze(0) * (
        1.0 + 3.0*cu + 4.5*cu**2 - 3.0*u_sq.unsqueeze(0))

def stream(f):
    f_s = torch.zeros_like(f)
    for i in range(9):
        f_s[i] = torch.roll(f[i], shifts=(int(c[i,0]), int(c[i,1])), dims=(0,1))
    return f_s

def bounceback(f, kappa):
    return (1.0 - kappa).unsqueeze(0) * f + kappa.unsqueeze(0) * f[opposite]

# ──────────────────────────────────────────────────────
# Laplace Vapor Diffusion Evaporation
# ──────────────────────────────────────────────────────
def compute_evaporation_laplace(rho, rho0, kappa, evap_coeff,
                                 c_sat=1.0, c_amb=0.3, iters=60):
    """
    Solve ∇²c = 0 for vapor concentration above the surface.
    BC: c = c_sat on wet cells, relaxes toward c_amb elsewhere.
    Evaporation flux J = |∇c| at wet boundary.
    """
    excess = (rho - rho0).clamp(min=0)
    wet = excess > 0.005

    if wet.sum() < 5:
        return torch.zeros_like(rho)

    # Initialize vapor field
    c_vapor = torch.ones_like(rho) * c_amb
    c_vapor[wet] = c_sat
    wet_float = wet.float()

    # Jacobi iteration for Laplace equation
    for _ in range(iters):
        c_new = 0.25 * (
            torch.roll(c_vapor, 1, 0) + torch.roll(c_vapor, -1, 0) +
            torch.roll(c_vapor, 1, 1) + torch.roll(c_vapor, -1, 1)
        )
        # Pin wet cells to saturation
        c_new = c_new * (1 - wet_float) + c_sat * wet_float
        c_vapor = c_new

    # Flux = gradient magnitude
    grad_x = (torch.roll(c_vapor, -1, 0) - torch.roll(c_vapor, 1, 0)) / 2
    grad_y = (torch.roll(c_vapor, -1, 1) - torch.roll(c_vapor, 1, 1)) / 2
    J = torch.sqrt(grad_x**2 + grad_y**2)

    # Only evaporate from wet cells, modulate by pore openness
    pore_factor = 1.0 - 0.3 * kappa
    J = evap_coeff * J * wet_float * pore_factor

    # Stability: don't remove more than 10% per step
    J = torch.min(J, excess * 0.1)
    return J

# ──────────────────────────────────────────────────────
# Initial Condition
# ──────────────────────────────────────────────────────
Y, X = torch.meshgrid(
    torch.arange(Nx, device=device, dtype=torch.float32),
    torch.arange(Ny, device=device, dtype=torch.float32), indexing='ij')
r = torch.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)

rho = torch.ones((Nx, Ny), device=device) * rho0
rho[r < drop_radius] = 1.5
u = torch.zeros((2, Nx, Ny), device=device)
f = equilibrium(rho, u)

# ──────────────────────────────────────────────────────
# Main Loop
# ──────────────────────────────────────────────────────
snapshots = []

print(f"Running {steps} steps...")
for step in range(steps):
    # Macroscopic quantities
    rho = f.sum(dim=0)
    momentum = torch.einsum('ic,ixy->cxy', c, f)
    u = momentum / (rho.unsqueeze(0) + 1e-10)

    # Collision + porous bounce-back + streaming
    feq = equilibrium(rho, u)
    f = stream(bounceback(f - omega * (f - feq), kappa))

    # Laplace-solved evaporation
    rho_post = f.sum(dim=0)
    J = compute_evaporation_laplace(rho_post, rho0, kappa, evap_coeff)
    f -= (J / (rho_post + 1e-10)).unsqueeze(0) * f

    if step in snap_at:
        rho_snap = f.sum(dim=0)
        excess = (rho_snap - rho0).clamp(min=0).cpu().numpy()
        mass = excess.sum()
        snapshots.append((step, excess.copy()))
        print(f"  Step {step:4d} | excess max={excess.max():.4f} | "
              f"total mass={mass:.1f}")

print("Done.")

# ──────────────────────────────────────────────────────
# Visualization
# ──────────────────────────────────────────────────────
ink_cmap = LinearSegmentedColormap.from_list('ink', [
    (1.0, 0.98, 0.94),
    (0.6, 0.62, 0.7),
    (0.25, 0.22, 0.38),
    (0.05, 0.03, 0.1)])

# --- Fiber network ---
fig, ax = plt.subplots(figsize=(6, 6))
ax.imshow(kappa.cpu().numpy(), cmap='bone_r', interpolation='nearest')
ax.set_title("Paper Fiber Network (κ field)", fontsize=13, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.show()

# --- Time evolution ---
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, (step, excess) in zip(axes.flat, snapshots):
    vmax = max(excess.max() * 0.85, 0.005)
    ax.imshow(excess, cmap=ink_cmap, vmin=0, vmax=vmax, interpolation='bilinear')
    ax.set_title(f"Step {step}", fontsize=11)
    ax.axis('off')
fig.suptitle("Ink Spreading with Fiber Network + Laplace Evaporation",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# --- Final hero render with paper texture ---
final_rho = f.sum(dim=0)
final_excess = (final_rho - rho0).clamp(min=0).cpu().numpy()

# Paper texture from the fiber field itself
paper_base = 1.0 - 0.06 * kappa_np  # fibers slightly darker
paper_grain = np.random.normal(0, 0.01, (Nx, Ny))
paper = paper_base + paper_grain

ink_opacity = np.clip(final_excess / max(final_excess.max() * 0.7, 0.001), 0, 1)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(paper, cmap='bone', vmin=0.88, vmax=1.05, interpolation='bilinear')
ax.imshow(final_excess, cmap=ink_cmap, vmin=0, vmax=max(final_excess.max()*0.75, 0.001),
          interpolation='bilinear', alpha=ink_opacity * 0.95)
ax.set_title("Final — Ink on Paper (Physics-Based)", fontsize=15, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.show()