# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWzo6XdkG-sneKzH8QAeXW9CiD_0kSo7
"""

"""
Two-field LBM ink-on-paper — two-stage version
- Stage 1: solvent LBM runs alone to produce a final shape h_final
- Stage 2: pigment transport runs on that frozen shape
"""

import os
import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# ============================================================
# Output folder
# ============================================================
out_dir = "lbm_ring_outputs"
os.makedirs(out_dir, exist_ok=True)
print(f"Saving figures to: {os.path.abspath(out_dir)}")

# ============================================================
# Parameters
# ============================================================
Nx, Ny = 712, 712
steps = 850
snap_at = [0, 200, 300, 500, 600, 849]

# LBM solvent
tau = 0.88
omega = 1.0 / tau
rho0 = 1.0

# Drop
drop_radius = 52
pin_radius = 63     # equilibrium wetted radius (where contact line pins)
spread_steps = 100    # steps before pin activates; drop spreads freely during this phase
rho_drop = 1.20
phi_init = 0.01

# Evaporation
evap_coeff = 0.007
laplace_iters = 80
c_sat = 1.0
c_amb = 0.25

# Pigment transport / deposition
D_phi = 0.251
deposit_rate = 0.4
thin_film_thresh = 0.16
max_phi = 1.0

# Ring support
pin_band = 10.5
pin_strength = 1.5

# ============================================================
# D2Q9
# ============================================================
c = torch.tensor([
    [0, 0], [1, 0], [0, 1], [-1, 0], [0, -1],
    [1, 1], [-1, 1], [-1, -1], [1, -1]
], dtype=torch.float32, device=device)

w = torch.tensor([
    4/9, 1/9, 1/9, 1/9, 1/9,
    1/36, 1/36, 1/36, 1/36
], dtype=torch.float32, device=device)

opposite = torch.tensor([0, 3, 4, 1, 2, 7, 8, 5, 6], dtype=torch.long, device=device)

# ============================================================
# Figure saving helper
# ============================================================
def savefig(name, dpi=180):
    path = os.path.join(out_dir, name)
    plt.savefig(path, dpi=dpi, bbox_inches="tight")
    print(f"Saved: {path}")

# ============================================================
# Fiber network
# ============================================================
def generate_fiber_network(nx, ny, n_fibers=300000, fiber_length=15, fiber_width=1, seed=42):
    np.random.seed(seed)
    field = np.zeros((nx, ny), dtype=np.float32)

    for _ in range(n_fibers):
        x0 = np.random.uniform(0, nx)
        y0 = np.random.uniform(0, ny)
        theta = np.random.uniform(0, np.pi)
        length = max(5, np.random.normal(fiber_length, fiber_length * 0.25))

        n_steps = int(length)
        ts = np.linspace(-length / 2, length / 2, n_steps)
        xs = (x0 + ts * np.cos(theta)).astype(int) % nx
        ys = (y0 + ts * np.sin(theta)).astype(int) % ny

        hw = fiber_width // 2
        for dx in range(-hw, hw + 1):
            for dy in range(-hw, hw + 1):
                if dx * dx + dy * dy <= (fiber_width / 2 + 0.5) ** 2:
                    field[(xs + dx) % nx, (ys + dy) % ny] += 1

    field = field / max(field.max(), 1)
    return field

print("Generating fiber network...")
kappa_np = generate_fiber_network(Nx, Ny)
kappa = torch.tensor(kappa_np, dtype=torch.float32, device=device)
kappa = 0.05 + 0.55 * kappa
print(f"kappa range: [{kappa.min().item():.3f}, {kappa.max().item():.3f}]")

# ============================================================
# Solvent LBM helpers
# ============================================================
def equilibrium(rho, u):
    cu = torch.einsum('ic,cxy->ixy', c, u)
    u_sq = 0.5 * (u[0]**2 + u[1]**2)
    return w.view(9, 1, 1) * rho.unsqueeze(0) * (
        1.0 + 3.0 * cu + 4.5 * cu**2 - 3.0 * u_sq.unsqueeze(0)
    )

def stream(f):
    out = torch.zeros_like(f)
    for i in range(9):
        out[i] = torch.roll(f[i], shifts=(int(c[i, 0]), int(c[i, 1])), dims=(0, 1))
    return out

def bounceback(f, kappa):
    return (1.0 - kappa).unsqueeze(0) * f + kappa.unsqueeze(0) * f[opposite]

# ============================================================
# Non-periodic helpers for pigment transport
# ============================================================
def pad_rep(field):
    return F.pad(field.unsqueeze(0).unsqueeze(0), (1, 1, 1, 1), mode='replicate')[0, 0]

def grad(field):
    f = pad_rep(field)
    gx = 0.5 * (f[2:, 1:-1] - f[:-2, 1:-1])
    gy = 0.5 * (f[1:-1, 2:] - f[1:-1, :-2])
    return gx, gy

def laplacian(field):
    f = pad_rep(field)
    return (
        f[2:, 1:-1] + f[:-2, 1:-1] +
        f[1:-1, 2:] + f[1:-1, :-2] -
        4.0 * f[1:-1, 1:-1]
    )

def advect_upwind(m, ux, uy):
    f = pad_rep(m)

    m_xp = f[2:, 1:-1]
    m_xm = f[:-2, 1:-1]
    m_yp = f[1:-1, 2:]
    m_ym = f[1:-1, :-2]

    dm_dx = torch.where(ux > 0, m - m_xm, m_xp - m)
    dm_dy = torch.where(uy > 0, m - m_ym, m_yp - m)

    return m - ux * dm_dx - uy * dm_dy

# ============================================================
# Evaporation
# ============================================================
def compute_evaporation_laplace(rho, rho0, kappa, evap_coeff, pin_mask, c_sat=1.0, c_amb=0.3, iters=60):
    excess = (rho - rho0).clamp(min=0)
    wet = excess > 0.003

    if wet.sum() < 5:
        return torch.zeros_like(rho), wet

    c_vapor = torch.ones_like(rho) * c_amb
    c_vapor[wet] = c_sat
    wet_f = wet.float()

    for _ in range(iters):
        c_new = 0.25 * (
            torch.roll(c_vapor, 1, 0) + torch.roll(c_vapor, -1, 0) +
            torch.roll(c_vapor, 1, 1) + torch.roll(c_vapor, -1, 1)
        )
        c_new = c_new * (1.0 - wet_f) + c_sat * wet_f
        c_vapor = c_new

    gx, gy = grad(c_vapor)
    J = torch.sqrt(gx**2 + gy**2)

    pore_factor = 1.0 - 0.35 * kappa
    rim_boost = 1.0 + 1.2 * pin_mask
    J = evap_coeff * J * wet_f * pore_factor * rim_boost
    J = torch.minimum(J, 0.08 * excess)
    return J, wet

# ============================================================
# Pigment transport
# ============================================================
def advect_diffuse_phi(phi, deposit, rho, u, J, kappa, pin_active):
    h = (rho - rho0).clamp(min=0)
    wet = h > 1e-8
    wet_f = wet.float()

    # mobile pigment mass
    m = phi * h

    # lower mobility in dense fiber regions
    drag = 0.1 - 0.1 * kappa

    # ------------------------------------------------------------------
    # Depth-averaged film velocity from mass conservation.
    # Contact line is pinned, so fluid removed by evaporation must be
    # replaced by in-plane flow: grad . (h u_film) = -J.  Writing
    # h u_film = grad(psi) gives Poisson:  laplacian(psi) = -J,
    # with psi = 0 on the dry region so no flux crosses the contact line.
    # Solving by Jacobi iteration using the pad_rep laplacian stencil.
    # ------------------------------------------------------------------
    psi = torch.zeros_like(h)
    src = -J * wet_f
    for _ in range(40):
        p = pad_rep(psi)
        psi_new = 0.25 * (
            p[2:, 1:-1] + p[:-2, 1:-1] +
            p[1:-1, 2:] + p[1:-1, :-2] - src
        )
        psi = psi_new * wet_f  # enforce psi=0 outside wet region

    gx_psi, gy_psi = grad(psi)
    inv_h = wet_f / (h + 1e-6)
    u_film_x = gx_psi * inv_h
    u_film_y = gy_psi * inv_h

    # stability cap
    u_film_x = torch.clamp(u_film_x, -0.08, 0.08)
    u_film_y = torch.clamp(u_film_y, -0.08, 0.08)

    ux = u[0] * drag + u_film_x
    uy = u[1] * drag + u_film_y

    # transport
    m_adv = advect_upwind(m, ux, uy)
    m_adv = m_adv + D_phi * laplacian(m)
    m_adv = torch.clamp(m_adv, min=0.0)

    # deposition strongly biased toward strong evaporation zones
    thin_factor = torch.clamp((thin_film_thresh - h) / thin_film_thresh, 0.0, 1.0)
    fiber_factor = 0.8 + 0.2 * kappa

    dep_prob = deposit_rate * (thin_factor ** 2) * fiber_factor * pin_active
    dep_prob = torch.clamp(dep_prob, 0.0, 0.25)

    dm_dep = dep_prob * m_adv * wet.float()
    m_mobile = m_adv - dm_dep
    deposit = deposit + dm_dep

    phi_new = torch.zeros_like(phi)
    phi_new[wet] = m_mobile[wet] / (h[wet] + 1e-10)
    phi_new = torch.clamp(phi_new, 0.0, max_phi)

    return phi_new, deposit

# ============================================================
# Diagnostics
# ============================================================
def radial_profile(field, cx, cy, n_bins=120):
    yy, xx = torch.meshgrid(
        torch.arange(field.shape[0], device=field.device),
        torch.arange(field.shape[1], device=field.device),
        indexing='ij'
    )
    rr = torch.sqrt((xx - cx)**2 + (yy - cy)**2)
    rr_i = torch.clamp(rr.long(), 0, n_bins - 1)

    sums = torch.zeros(n_bins, device=field.device)
    counts = torch.zeros(n_bins, device=field.device)

    sums.scatter_add_(0, rr_i.flatten(), field.flatten())
    counts.scatter_add_(0, rr_i.flatten(), torch.ones_like(field).flatten())

    return (sums / (counts + 1e-10)).detach().cpu().numpy()

# ============================================================
# Geometry
# ============================================================
Y, X = torch.meshgrid(
    torch.arange(Nx, device=device, dtype=torch.float32),
    torch.arange(Ny, device=device, dtype=torch.float32),
    indexing='ij'
)

cx0, cy0 = Nx // 2, Ny // 2
dx = X - cy0
dy = Y - cx0
theta = torch.atan2(dy, dx)
r = torch.sqrt(dx**2 + dy**2)

# --- uneven blob radius as a function of angle ---
base_radius = 52.0
r_blob = (
    base_radius
    + 1.0 * torch.sin(3.0 * theta)
    + 2.0 * torch.sin(7.0 * theta + 0.8)
    + 1.5 * torch.cos(5.0 * theta - 0.4)
)

inside = r < r_blob

rho = torch.ones((Nx, Ny), device=device) * rho0
rho[inside] = rho_drop

u = torch.zeros((2, Nx, Ny), device=device)
f = equilibrium(rho, u)

deposit = torch.zeros((Nx, Ny), device=device)

# --- blob-shaped pin: same angular profile as r_blob, scaled to pin_radius ---
r_pin_blob = r_blob * (pin_radius / base_radius)

pin_mask = ((r > r_pin_blob - pin_band) & (r < r_pin_blob + pin_band)).float()

# Hard pin: fixed wet domain follows the blob shape
wet_domain = (r <= r_pin_blob).float()
pin_wall = ((r > r_pin_blob) & (r <= r_pin_blob + 2)).float()  # 2-cell shell

# ============================================================
# Stage 1 — solvent only
# ============================================================
snapshots = []
profiles = []
stage1_solvent_snaps = {}

# Animation frames
anim_stride = 25
stage1_frames = []
stage2_frames = []

print(f"Stage 1: running {steps} solvent steps...")
for step in range(steps):
    f = torch.nan_to_num(f, nan=0.0, posinf=0.0, neginf=0.0)
    f = torch.clamp(f, min=0.0)
    rho = f.sum(dim=0).clamp(min=1e-6)
    momentum = torch.einsum('ic,ixy->cxy', c, f)
    u = momentum / (rho.unsqueeze(0) + 1e-10)

    # pin activation: zero during spreading phase, ramps to 1 over 50 steps
    pin_active = max(0.0, min(1.0, (step - spread_steps) / 50.0))
    active_pin_mask = pin_mask * pin_active

    # hard pin: bounce-back wall on the ring of Ω
    kappa_eff = torch.clamp(kappa + pin_active * pin_wall, 0.0, 1.0)

    u_forced = torch.clamp(u, -0.1, 0.1)

    # solvent collide/stream
    feq = equilibrium(rho, u_forced)
    f = f - omega * (f - feq)
    f = bounceback(f, kappa_eff)
    f = stream(f)

    # damp velocity near the wall to kill inward reflections
    if pin_active > 0.5:
        damp_band = ((r > r_pin_blob - 3) & (r <= r_pin_blob)).float()
        rho_local = f.sum(dim=0)
        u_local = torch.einsum('ic,ixy->cxy', c, f) / (rho_local.unsqueeze(0) + 1e-10)
        u_damped = u_local * (1.0 - 0.8 * damp_band).unsqueeze(0)
        f_relax = equilibrium(rho_local, u_damped)
        f = f * (1.0 - damp_band).unsqueeze(0) + f_relax * damp_band.unsqueeze(0)

    # evaporation
    rho_post = f.sum(dim=0)
    J, wet = compute_evaporation_laplace(
        rho_post, rho0, kappa, evap_coeff, active_pin_mask,
        c_sat=c_sat, c_amb=c_amb, iters=laplace_iters
    )
    excess = (rho_post - rho0).clamp(min=1e-10)
    evap_frac = torch.clamp(J / excess, 0.0, 0.20)
    f = f - evap_frac.unsqueeze(0) * (
        f - equilibrium(torch.ones_like(rho_post) * rho0, torch.zeros_like(u))
    )

    if step % 500 == 0:
        h_dbg = (f.sum(dim=0) - rho0).clamp(min=0)
        print(f"  stage1 step {step:4d} | solvent excess={h_dbg.sum().item():10.3f}")

    if step in snap_at:
        h_s1 = (f.sum(dim=0) - rho0).clamp(min=0)
        stage1_solvent_snaps[step] = h_s1.detach().cpu().numpy().copy()

    if step % anim_stride == 0:
        h_anim = (f.sum(dim=0) - rho0).clamp(min=0)
        stage1_frames.append(h_anim.detach().cpu().numpy().copy())

# freeze the final shape
rho_final = f.sum(dim=0)
h_final = (rho_final - rho0).clamp(min=0)
footprint = (h_final > 1e-3).float()
print(f"Stage 1 done. Footprint cells: {int(footprint.sum().item())}")

# ============================================================
# Stage 2 — pigment on the frozen shape
# ============================================================
phi = torch.zeros((Nx, Ny), device=device)
phi[footprint > 0.5] = phi_init
deposit = torch.zeros((Nx, Ny), device=device)

# Frozen solvent that the pigment code will see.
rho_frozen = rho0 + h_final
u_frozen = torch.zeros((2, Nx, Ny), device=device)

stage2_steps = steps
stage2_snap_at = snap_at

print(f"Stage 2: running {stage2_steps} pigment steps on frozen shape...")

# Rescale stage 1's final shape so its peak matches a fresh drop.
# This preserves the relative density gradient from stage 1 but gives
# the pigment code a full-height film to work with.
h0_stage2 = rho_drop - rho0   # 0.20, same as the original drop peak
h_final_max = h_final.max().clamp(min=1e-6)
h_final_scaled = h_final * (h0_stage2 / h_final_max)

# soften the edge so deposition doesn't concentrate on a cliff
for _ in range(8):
    p = pad_rep(h_final_scaled)
    h_final_scaled = 0.25 * (p[2:,1:-1] + p[:-2,1:-1] + p[1:-1,2:] + p[1:-1,:-2])

# thin ring at the edge of the smoothed shape, for rim evaporation boost
edge_mask = ((h_final_scaled > 0.02).float() - (h_final_scaled > 0.05).float()).clamp(min=0)

print(f"  rescaled h_final: old max={h_final_max.item():.4f} -> new max={h_final_scaled.max().item():.4f}")

for step in range(stage2_steps):
    # nonlinear thinning: fast at first, slower later — crosses the deposition
    # threshold around the middle of the run so deposition has time to build up
    t = step / stage2_steps
    decay = max(0.05, (1.0 - t) ** 0.6)
    h_t = h_final_scaled * decay
    rho_frozen_t = rho0 + h_t

    # live evaporation on the thinning shape — drives u_film in advect_diffuse_phi
    J, wet = compute_evaporation_laplace(
        rho_frozen_t, rho0, kappa, evap_coeff, edge_mask,
        c_sat=c_sat, c_amb=c_amb, iters=laplace_iters
    )

    # pigment transport
    phi, deposit = advect_diffuse_phi(
        phi, deposit, rho_frozen_t, u_frozen, J, kappa, pin_active=1.0
    )

    if step % anim_stride == 0:
        stage2_frames.append({
            "h": h_t.detach().cpu().numpy().copy(),
            "deposit": deposit.detach().cpu().numpy().copy(),
        })

    if step in stage2_snap_at:
        mobile_pigment = phi * h_t

        snapshots.append({
            "step": step,
            "solvent": stage1_solvent_snaps.get(step, h_final.detach().cpu().numpy().copy()),
            "mobile": mobile_pigment.detach().cpu().numpy().copy(),
            "deposit": deposit.detach().cpu().numpy().copy(),
            "J": J.detach().cpu().numpy().copy(),
        })

        profiles.append({
            "step": step,
            "mobile": radial_profile(mobile_pigment, cx0, cy0),
            "deposit": radial_profile(deposit, cx0, cy0),
        })

        print(
            f"  stage2 step {step:4d} | "
            f"mobile pigment={mobile_pigment.sum().item():10.3f} | "
            f"deposit={deposit.sum().item():10.3f}"
        )

print("Done.")

# ============================================================
# Visualization
# ============================================================
ink_cmap = LinearSegmentedColormap.from_list('ink', [
    (1.0, 0.98, 0.94),
    (0.75, 0.76, 0.82),
    (0.38, 0.33, 0.50),
    (0.08, 0.05, 0.12)
])

dep_cmap = LinearSegmentedColormap.from_list('dep', [
    (0.97, 0.98, 1.00),
    (0.70, 0.80, 0.92),
    (0.25, 0.45, 0.75),
    (0.04, 0.08, 0.25)
])

# --- Fiber field ---
fig, ax = plt.subplots(figsize=(6, 6))
ax.imshow(kappa.cpu().numpy(), cmap='bone_r', interpolation='nearest')
ax.set_title("Paper Fiber Network (κ field)", fontsize=13, fontweight='bold')
ax.axis('off')
plt.tight_layout()
savefig("01_fiber_network.png")
plt.show()

# --- Solvent snapshots (all show h_final) ---
vmax_solvent = max(snapshots[0]["solvent"].max() * 0.9, 1e-3)
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, snap in zip(axes.flat, snapshots):
    ax.imshow(snap["solvent"], cmap='Blues', vmin=0, vmax=vmax_solvent, interpolation='bilinear')
    ax.set_title(f"Solvent (stage 1) step {snap['step']}")
    ax.axis('off')
fig.suptitle("Solvent film (stage 1 final shape)", fontsize=14, fontweight='bold')
plt.tight_layout()
savefig("02_solvent_snapshots.png")
plt.show()

# --- Mobile pigment snapshots ---
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, snap in zip(axes.flat, snapshots):
    img = snap["mobile"]
    vmax = max(img.max() * 0.9, 1e-4)
    ax.imshow(img, cmap=ink_cmap, vmin=0, vmax=vmax, interpolation='bilinear')
    ax.set_title(f"Mobile pigment step {snap['step']}")
    ax.axis('off')
fig.suptitle("Pigment still in the liquid", fontsize=14, fontweight='bold')
plt.tight_layout()
savefig("03_mobile_pigment_snapshots.png")
plt.show()

# --- Deposited pigment snapshots ---
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, snap in zip(axes.flat, snapshots):
    img = snap["deposit"]
    vmax = max(img.max() * 0.9, 1e-4)
    ax.imshow(img, cmap=dep_cmap, vmin=0, vmax=vmax, interpolation='bilinear')
    ax.set_title(f"Deposit step {snap['step']}")
    ax.axis('off')
fig.suptitle("Deposited pigment on paper", fontsize=14, fontweight='bold')
plt.tight_layout()
savefig("04_deposit_snapshots.png")
plt.show()

# --- Evaporation snapshots ---
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, snap in zip(axes.flat, snapshots):
    img = snap["J"]
    vmax = max(img.max() * 0.95, 1e-6)
    ax.imshow(img, cmap='magma', vmin=0, vmax=vmax, interpolation='bilinear')
    ax.set_title(f"Evaporation flux step {snap['step']}")
    ax.axis('off')
fig.suptitle("Evaporation flux J", fontsize=14, fontweight='bold')
plt.tight_layout()
savefig("05_evaporation_flux_snapshots.png")
plt.show()

# --- Final deposit-only render ---
final_solvent = snapshots[-1]["solvent"]
final_mobile = snapshots[-1]["mobile"]
final_deposit = snapshots[-1]["deposit"]

paper_base = 1.0 - 0.0 * kappa_np
paper_grain = np.random.normal(0, 0.000001, (Nx, Ny))
paper = np.clip(paper_base + paper_grain, 0.86, 1.05)

dep_norm = final_deposit / max(final_deposit.max(), 1e-8)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(paper, cmap='bone', vmin=0.88, vmax=1.05, interpolation='bilinear')
ax.imshow(
    final_deposit,
    cmap=dep_cmap,
    vmin=0,
    vmax=max(final_deposit.max() * 0.85, 1e-4),
    alpha=np.clip(dep_norm * 1.1, 0, 1),
    interpolation='bilinear'
)
ax.set_title("Final — deposited pigment only", fontsize=15, fontweight='bold')
ax.axis('off')
plt.tight_layout()
savefig("06_final_deposit_only.png")
plt.show()

# --- Final mobile pigment render ---
mob_norm = final_mobile / max(final_mobile.max(), 1e-8)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(paper, cmap='bone', vmin=0.88, vmax=1.05, interpolation='bilinear')
ax.imshow(
    final_mobile,
    cmap=ink_cmap,
    vmin=0,
    vmax=max(final_mobile.max() * 0.9, 1e-4),
    alpha=np.clip(mob_norm, 0, 1),
    interpolation='bilinear'
)
ax.set_title("Final — remaining mobile pigment", fontsize=15, fontweight='bold')
ax.axis('off')
plt.tight_layout()
savefig("07_final_mobile_pigment.png")
plt.show()

# --- Deposit radial profiles ---
plt.figure(figsize=(9, 5))
for p in profiles:
    plt.plot(p["deposit"], label=f"deposit step {p['step']}")
plt.xlim(0, 80)
plt.xlabel("Radius (pixels)")
plt.ylabel("Azimuthal mean deposited pigment")
plt.title("Deposited pigment radial profile")
plt.legend()
plt.tight_layout()
savefig("08_deposit_radial_profiles.png")
plt.show()

# --- Mobile radial profiles ---
plt.figure(figsize=(9, 5))
for p in profiles:
    plt.plot(p["mobile"], label=f"mobile step {p['step']}")
plt.xlim(0, 80)
plt.xlabel("Radius (pixels)")
plt.ylabel("Azimuthal mean mobile pigment")
plt.title("Mobile pigment radial profile")
plt.legend()
plt.tight_layout()
savefig("09_mobile_radial_profiles.png")
plt.show()

print("\nAll figures saved.")
print("You should check 04_deposit_snapshots.png, 06_final_deposit_only.png, and 08_deposit_radial_profiles.png first.")

# ============================================================
# Animation: stage 1 solvent, then stage 2 deposit building on it
# ============================================================
import matplotlib.animation as animation

print("\nBuilding animation...")

# colormaps & scales
vmax_solvent_anim = max(max((frm.max() for frm in stage1_frames), default=1e-3), 1e-3)
vmax_deposit_anim = max(
    max((frm["deposit"].max() for frm in stage2_frames), default=1e-4),
    1e-4,
)
h_final_np = h_final_scaled.detach().cpu().numpy()
vmax_h_final = max(h_final_np.max() * 0.9, 1e-3)

fig_anim, ax_anim = plt.subplots(figsize=(7, 7))
ax_anim.axis("off")

# initial frame: stage 1 first frame
solvent_im = ax_anim.imshow(
    stage1_frames[0], cmap="Blues", vmin=0, vmax=vmax_solvent_anim,
    interpolation="bilinear",
)
deposit_im = ax_anim.imshow(
    np.zeros_like(stage1_frames[0]), cmap=dep_cmap,
    vmin=0, vmax=vmax_deposit_anim, alpha=0.0, interpolation="bilinear",
)
title = ax_anim.set_title("Stage 1 — solvent step 0", fontsize=13, fontweight="bold")

n1 = len(stage1_frames)
n2 = len(stage2_frames)
total_frames = n1 + n2

def update(frame_idx):
    if frame_idx < n1:
        # stage 1: show solvent evolving, deposit hidden
        solvent_im.set_data(stage1_frames[frame_idx])
        solvent_im.set_clim(0, vmax_solvent_anim)
        deposit_im.set_alpha(0.0)
        title.set_text(f"Stage 1 — solvent step {frame_idx * anim_stride}")
    else:
        # stage 2: stage 1's final shape held constant, deposit building on top
        i2 = frame_idx - n1
        frm = stage2_frames[i2]
        solvent_im.set_data(h_final_np)
        solvent_im.set_clim(0, vmax_h_final)
        dep = frm["deposit"]
        dep_norm = dep / max(dep.max(), 1e-8)
        deposit_im.set_data(dep)
        deposit_im.set_alpha(np.clip(dep_norm * 1.1, 0, 1))
        title.set_text(f"Stage 2 — deposit step {i2 * anim_stride}")
    return solvent_im, deposit_im, title

ani = animation.FuncAnimation(
    fig_anim, update, frames=total_frames, interval=50, blit=False
)

anim_path = os.path.join(out_dir, "10_full_run.mp4")
try:
    ani.save(anim_path, writer="ffmpeg", fps=20, dpi=140)
    print(f"Saved: {anim_path}")
except Exception as e:
    print(f"ffmpeg save failed ({e}); falling back to GIF")
    anim_path_gif = os.path.join(out_dir, "10_full_run.gif")
    ani.save(anim_path_gif, writer="pillow", fps=15, dpi=100)
    print(f"Saved: {anim_path_gif}")

plt.close(fig_anim)